### ISSUE TITLE
Map not centered

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#114]
When navigating to the map from the home page, the map isn't centered.

[Video.webm](https://user-images.githubusercontent.com/13600696/221064147-cdc4fdcd-b87f-432b-9ad5-a924df78be76.webm)

**Comment by Flizzyclone** [comment]
Problem is related to how the side bar transitions, because of the transition, when panZoom is called, the svg element is a different size than it is when the transition is completed.
