### ISSUE TITLE
State visibility

### ISSUE THREAD

**Issue by DexterzStoodio** [yapms/YAPms#119]
The user would be able to edit weather a state would be visible or not. It would be like disabling a state, but instead of it being greyed out it is removed from the map

**Comment by Flizzyclone** [comment]
Easy to do w/ CSS opacity and setting value to 0 on region. IMO, this is something that would be valuable. Wdyt, @Fish1?

**Comment by Fish1** [comment]
I'm kinda against it because it would be confusing to re-enable a state, as you'd need to click on something you cannot see. But you can make a demo PR if you'd like.

**Comment by DexterzStoodio** [comment]
@Fish1  I think to fix the issue with re-enabling states would be to make a remove state mode. While in the mode states you remove would be greyed out, and then when you exit the mode they'd be removed, and if you wanted to readd a state you just go back into that mode and enable it.

**Comment by Fish1** [comment]
This can be reopened if it will be worked on.
