### ISSUE TITLE
YAPMS text on sidebar covers links

### ISSUE THREAD

**Issue by Rexogamer** [yapms/YAPms#17]
![B56D528C-3AD3-46A3-AE9C-775B1B2AA61D](https://user-images.githubusercontent.com/42586271/66950041-8ec70100-f04f-11e9-8013-094ae2f91a0a.jpeg)

**Comment by Fish1** [comment]
Thank you! That is a very strange glitch that happens on Apple devices. But I've been trying to fix it but I don't have an apple product to test it on.
