### ISSUE TITLE
Ec edit world

### ISSUE THREAD

**Issue by Andreimapper** [yapms/YAPms#19]
No EC edit world and the smaller places are hard to color.

**Comment by Kite-cloud-code** [comment]
Yes if you're on a computer and don't have an easy drag and zoom function the smaller areas are hard to fill in. Try accessing it on a mobile device. I find it's a lot easier

**Comment by Andreimapper** [comment]
But that is still hard and I have tried it and it does not fill

**Comment by Julio974-TheHexahedron** [comment]
I'll add the EC edit for that map if it's not already possible
