### ISSUE TITLE
Blurriness on imported maps (and regular maps)

### ISSUE THREAD

**Issue by CenterRightPatriot** [yapms/YAPms#192]
When I import something or use a map, it comes out blurry on mobile.

**Comment by Flizzyclone** [comment]
Hi there! Thanks for the report. In order to track this issue down, could you tell us which phone you're using?

**Comment by CenterRightPatriot** [comment]
Hi! I tried it on 3 different devices

iPhone SE (2nd)
iPad 7th Gen
iPad Air 2

**Comment by CenterRightPatriot** [comment]
![81F7C147-8CCF-47DC-A45E-3C2E544AECF9](https://github.com/yapms/yapms/assets/137594648/1adb6a3a-bc0e-4aa5-9ecd-1fa31e7224fe)

**Comment by Flizzyclone** [comment]
Ooh I see. Thanks for the report!

**Comment by CenterRightPatriot** [comment]
Basically the size automatically changes when zooming in. It is fine for states like Oklahoma, Connecticut or Iowa, but in states with population concentrated in one area (a major city like LA or NY), it is a problem.


![986114D9-1EE6-456B-AB24-C5C24FDC9715](https://github.com/yapms/yapms/assets/137594648/9df326cc-81cd-4241-a019-669543c6fad2)
![E4D939EE-748D-4F37-8F58-5921B784DC27](https://github.com/yapms/yapms/assets/137594648/66fa1b38-471e-4d84-82c4-59613a866e03)

this problem is only on yapms2 and not on yapms
![42C25080-2A9A-428A-A33E-920100556E41](https://github.com/yapms/yapms/assets/137594648/40783a9f-7cf7-418f-b4ad-25e5ae1d3a0c)

**Comment by CenterRightPatriot** [comment]
ok so no fix?

**Comment by Fish1** [comment]
duplicate of https://github.com/yapms/yapms/issues/261
