### ISSUE TITLE
Border size slider for imported maps

### ISSUE THREAD

**Issue by Flizzyclone** [yapms/YAPms#194]
Imported maps have such variety that we cannot reasonably assume that the default border size will work well on all maps.

To fix that we should add a slider somewhere (import modal?) to switch the border size between either a couple of preset sizes or a percentage value that we multiply the default size by.

**Comment by CenterRightPatriot** [comment]
Yes

**Comment by Flizzyclone** [comment]
This can be expanded to all maps now as all use auto borders.
