### ISSUE TITLE
Random Extra District 

### ISSUE THREAD

**Issue by CenterRightPatriot** [yapms/YAPms#198]
I imported a map of Colorado with 8 disteict, and there is a random tossup that doesn’t exist
![5F9C61CC-8FE5-41C2-A90D-7C3A6005C3D5](https://github.com/yapms/yapms/assets/137594648/091d9846-76f2-483c-9c3f-410c8e6fe447)

**Comment by Flizzyclone** [comment]
Placing this on the backlog, as it likely isn't an issue w/ yapms

**Comment by CenterRightPatriot** [comment]
What is it then? When I did the Redistricting every block was assigned

**Comment by CenterRightPatriot** [comment]
it was a redistricting issue with the website i was using to draw
