### ISSUE TITLE
GeoJSON files that cross the 180th meridian end being super wide when imported

### ISSUE THREAD

**Issue by KraiGitHub** [yapms/YAPms#201]
How should YAPMS deal with GeoJSON files that cross the 180th meridian? If I give an AK GeoJSON from DRA to YAPMS 2 the map will be super zoomed out and I will barely be able to click on Anchorage's districts even at max zoom because the GeoJSON will technically be 360 degrees wide, spanning the whole world West to East. Something similar could happen to Russia but the main case really is just any map that has Alaska in it.

Maybe YAPMS could figure out some way to figure out where the 180th degree would be nearest to the mainland and then put the islands on the other side of this imaginary nearby line, and thus right next to the mainland.

![Captura de tela 2023-06-27 194903](https://github.com/yapms/yapms/assets/137658832/1a491c14-2eee-43d4-a69d-47705603e6d2)

**Comment by Flizzyclone** [comment]
woah is that why that does that? shooot good catch

**Comment by Fish1** [comment]
@Flizzyclone is this actually an issue? Or just a limitation of importing from GeoJSON?

I think we can close this?

**Comment by Flizzyclone** [comment]
I have not identified a fix to this. If there is a fix, that's probably not one we can have be done automatically. We can close this.
