### ISSUE TITLE
Disable Region Feature

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#21]
After the rework, the disable feature needs to be recreated.

Global data will be in the stores now, instead of in the +page file. I think the state of the keyboard should also be handled in a store.

![image](https://user-images.githubusercontent.com/13600696/205811954-ca092d4a-ca80-4b35-a7fc-d18ed4e15b8a.png)

**Comment by Fish1** [comment]
@Flizzyclone I cant seem to assign you to the issue, maybe you need to leave a comment?

![image](https://user-images.githubusercontent.com/13600696/205812343-b1aa3ff7-b668-4f10-8032-f2589e26e127.png)

**Comment by Flizzyclone** [comment]
Here's a comment!
