### ISSUE TITLE
New map using colors from old map

### ISSUE THREAD

**Issue by Flizzyclone** [yapms/YAPms#216]
Lysander felix on the Discord encountered an issue on IPad where he used the Canadian map for a bit and when he switched onto another map it still registered him as using a previous color.
![](https://cdn.discordapp.com/attachments/1038875464602763365/1126900934094626956/IMG_1883.png)

I cannot immediately reproduce this, and iirc we have protection built in against this?

**Comment by Lysander** [comment]
You probably mean someone else - I am not involved here at all.

**Comment by Flizzyclone** [comment]
Oops! My bad, didn't think that would actually ping.

**Comment by Lysander** [comment]
No Problem 😃👍
