### ISSUE TITLE
Map Blurred / Border is not very clear

### ISSUE THREAD

**Issue by CenterRightPatriot** [yapms/YAPms#261]
As you can see in the images below, the map I uploaded is extremely blurry, and I especially can’t color places like NYC or LA as they are too blurry. This only happens on yapms2 and not yapms, which could be due to the lines being smoother on yapms, and that the size doesn’t auto rechange, or it could be a graphics issue somewhere.

yapms2 imported map view:
![26F1E42F-0221-4F87-91DF-959B8949A1FE](https://github.com/yapms/yapms/assets/137594648/f0d5c67a-67ec-412b-953e-63d3228212b9)
![BA501D08-1736-4AAB-94B2-1AE4EC05C171](https://github.com/yapms/yapms/assets/137594648/1c66c4fa-45ac-49d9-960e-9ef2f5131825)

regular yapms
![9874B861-B17B-4A31-A954-94937AA2C0D7](https://github.com/yapms/yapms/assets/137594648/040c8925-512a-4a35-9041-ec9155ef3c18)

**Comment by CenterRightPatriot** [comment]
Do I need a different redistricting site? Or does anyone else get this (I am on mobile)

**Comment by Flizzyclone** [comment]
I believe this is related to #192, which we have not been able to fix yet. Problem does not manifest on desktop.

**Comment by CenterRightPatriot** [comment]
ok maybe make resolution clearer on mobile somehow, or make the line thinner so you can see small districts clearly and this doesn’t occur
![790C2EF6-13EF-4783-B825-29FC6D019B20](https://github.com/yapms/yapms/assets/137594648/3084c3ef-bef5-4ad6-9421-75d8d3347429)

**Comment by Fish1** [comment]
@Firecyyy please avoid making duplicate issues.

I'll close the other one in favor of this one.
