### ISSUE TITLE
Edit candidate modal colors error

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#4]
Deleting all colors from the edit candidate modal, results in all modal functionality to stop.

![image](https://user-images.githubusercontent.com/13600696/200712682-ded529db-7c93-4b84-9dfa-7bb049c5f2ec.png)

**Comment by Flizzyclone** [comment]
Going to work fix this one by making it so you can't remove all colors

**Comment by Fish1** [comment]
This has been fixed on the PR to upgrade to stores.
