### ISSUE TITLE
Readme Creation

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#44]
The project needs a Read-Me to direct people towards what they are looking for.

Examples...
1) Docker Setup
2) Setup project and build
3) Map creation
4) Contribution guidelines

**Comment by Flizzyclone** [comment]
We might need more extensive documentation than just a readme as well using something like Github Pages.

**Comment by Fish1** [comment]
I started putting stuff in the GitHub wiki.

https://github.com/yapms/yapms/wiki/Map-SVG-Format
