### ISSUE TITLE
Odd map behavior when changing chart position.

### ISSUE THREAD

**Issue by Flizzyclone** [yapms/YAPms#46]
When chart in side position, the map doesn't fill it's entire space and is relegated to the top middle.
![image](https://user-images.githubusercontent.com/42476312/208220550-9c0be841-7b1f-4f00-ab63-857cb8f6a445.png)

Removal of this transform tag applied to the svg element itself fixes it but results in unintended behavior for the bottom chart position:
![image](https://user-images.githubusercontent.com/42476312/208220566-8b93bc01-3e12-4274-ba34-7df6395d9d2d.png)

![image](https://user-images.githubusercontent.com/42476312/208220578-9aac813b-89e7-4a76-aaca-646e7e1efabc.png)

**Comment by Fish1** [comment]
I think in old yapms, I just forced the map to recenter whenever the window size changed, or the position of the chart changed.

This feature should be build into the pan-zoom library we're using.
