### ISSUE TITLE
Add borders to regions.

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#48]
Every region needs a border, this will make the maps look much better.

In old yapms, I programmatically applied borders to everything, because I am terrible at making SVG graphics. 

Should we add borders programmatically? Or have the map makers build borders into the maps?

New YAPms:
![image](https://user-images.githubusercontent.com/13600696/208221652-ba3ec2ac-e65e-470b-9072-9f2056292a4f.png)

Old YAPms:
![image](https://user-images.githubusercontent.com/13600696/208221658-eb125d18-a1a0-450d-8340-b4fa7ce0168b.png)

**Comment by Flizzyclone** [comment]
This seems best to leave to mapmakers imo. "Official" SVGs made by us can have a consistent set of styles. We can write up how to conform to these styles in the guide on how3 to make maps.

**Comment by Fish1** [comment]
Sounds good! Guess we just have to fix the SVG as some point then.

**Comment by Flizzyclone** [comment]
We might be able to do this and make map-making easier by including pre-made "Official" styles within the app thru CSS.
