### ISSUE TITLE
Sidebar title should be user friendly.

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#5]
/app/usa/presidential/2022 should be 'USA 2022 Presidential Election' or something similar.

![image](https://user-images.githubusercontent.com/13600696/200712827-18b5760a-8ff2-4c7f-b304-d96b7f1b9a7f.png)

**Comment by Flizzyclone** [comment]
Do you want this done dynamically based on URL or based on a file like Titles.json?

**Comment by Fish1** [comment]
The Titles.json idea might be better, because then we can have any title we want without it being pre-determined by the URL.
