### ISSUE TITLE
Histproc US House Maps are blank

### ISSUE THREAD

**Issue by Mav12222** [yapms/YAPms#512]
None of the maps under the "Historical USA House" maps on the website actually display the election results.  They are just blank maps of the house map of that time. All other historical maps work fine, its just the ones in the "Historical USA House" that dont work.

**Comment by Flizzyclone** [comment]
Yeah sorry there should be some better clarification there. Those are the historical lines instead of the results. Maybe I should make them results only and you can clear instead. Working as intended.
