### ISSUE TITLE
"Save maps" not working

### ISSUE THREAD

**Issue by lol9214** [yapms/YAPms#513]
I am currently working on a national county map. I have completed abut 30 states so far, and every time I try to work on it, I save the progress after every state. But now if I edit even a single county and try to save the map, it will not load.

**Comment by Fish1** [comment]
Does it work now?

**Comment by lol9214** [comment]
No

**Comment by Fish1** [comment]
Can you screenshot your map, and put it here?

**Comment by Fish1** [comment]
Also, can you do a "download" and put the downloaded file here?
