### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#60]
The homepage needs a general layout.

Feel free to make any suggestions, or mockups here.

**Comment by Flizzyclone** [comment]
Had an idea where we have semi-transparent flag backgrounds on the card component so that they blend in with the existing card background. Tried working on some CSS to do this, didn't turn out great.

**Comment by Fish1** [comment]
Have you looked at daisyui's example? Is this what you're looking to do?

https://daisyui.com/components/card/

![image](https://user-images.githubusercontent.com/13600696/209275647-53b946a5-a69b-4bd0-8548-2636b10bfae4.png)

**Comment by Flizzyclone** [comment]
That's what I'm looking for, I tried it and unfortunately I think it doesn't look great.

**Comment by Flizzyclone** [comment]
![image](https://user-images.githubusercontent.com/42476312/209598706-c913983b-4a69-441c-b8e1-9cbcdf744a38.png)
using this card design, also adding updates and a login button (both will be unfunctional on PR)

also needed will be a modal for if a country has a bunch of maps, modal will be generic and allow data to be passed to it in-client, from which point it will be constructed. Most likely will look like the dropdown modals.
