### ISSUE TITLE
panZoom doesn't apply to maps

### ISSUE THREAD

**Issue by Flizzyclone** [yapms/YAPms#67]
panZoom doesn't apply to maps with an id other than "testing-map".

since node is a div containing only the map svg, we can do the following:
![image](https://user-images.githubusercontent.com/42476312/209417181-d465740c-ec25-4fbf-b2ac-1df694cd7e78.png)

**Comment by Flizzyclone** [comment]
might want to change the maxZoom also

**Comment by Fish1** [comment]
Sounds good!

**Comment by Fish1** [comment]
This was fixed in #70
