### ISSUE TITLE
2024 french Legislative election Map

### ISSUE THREAD

**Issue by Hosain1291** [yapms/YAPms#685]
Hello, it's been a while. This is Hosain. The reason I am writing this is because France recently dissolved its parliament and will hold elections again. Therefore, I am requesting an updated map of the French parliamentary constituencies. If it's difficult to find a Polygon or GeoJSON format, an SVG format will be fine. Anyway, since the first round of the French parliamentary elections is on June 30 and the second round is on July 7, I would appreciate it if you could make it as soon as possible, or at least as soon as you have time. Thank you.

**Comment by Fish1** [comment]
closed by #691
