### ISSUE TITLE
Map SVG format update

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#71]
The SVG map format should be finalized.

Should be able to identify regions via custom attributes, not the class attribute.

**Comment by Flizzyclone** [comment]
Is this the only thing left to finalize it?

**Comment by Fish1** [comment]
That was just the first thing that came to mind. Do you have any suggestions?

**Comment by Flizzyclone** [comment]
I think similar to the way we do candidates, we might want to put in an attribute for links to resources about the map on the sidebar. Though this isn't crucial for now and could be added in later.

**Comment by Flizzyclone** [comment]
Just doing the region via custom attribute for now. PR soon
