### ISSUE TITLE
Page keeps crashing whenever I choose an election from Historical Presidential Elections

### ISSUE THREAD

**Issue by MrFancypants6** [yapms/YAPms#750]
I'm not sure what is going on, but I keep trying to choose the 1912 Presidential Election for example and whenever I choose to select a candidate to give them a state, the page then crashes. It keeps doing this over and over again and it's the same for other election choices too. So, I'm just putting this to your attention so that something can be done about it.
![image_2024-07-15_123756891](https://github.com/user-attachments/assets/3135d65d-3446-429c-afd7-b6d082b24993)

**Comment by jjjclarke** [comment]
What browser (and version) are you using?

**Comment by MrFancypants6** [comment]
> What browser (and version) are you using?

Opera GX

**Comment by Fish1** [comment]
Duplicate #784
