### ISSUE TITLE
page crashes when certain actions are taken

### ISSUE THREAD

**Issue by fiyum** [yapms/YAPms#763]
i can open the website and go to a map, but once i zoom with the middle mouse button or click on a candidate the page crashes. this has been happening for weeks now and there's been no apparent fix for it. i use Opera GX in case anyone needs to know the browser this is happening on.

**Comment by Ha33aJ** [comment]
I have the same issue with Opera GX, it's any form of interacting with the maps. The site itself seems to be fine just crashes when using the map

**Comment by Fish1** [comment]
Duplicate #784
