### ISSUE TITLE
Split does not work in states/territories map

### ISSUE THREAD

**Issue by duskywing** [yapms/YAPms#770]
The sliders do not move.

**Comment by Fish1** [comment]
Could you provide a link to the map?

**Comment by duskywing** [comment]
https://yapms.com/app/usa/states_and_territories/2023001/blank

**Comment by Fish1** [comment]
It doesn't work when you pull it past the halfway point like this?

[Screencast from 2024-07-22 23-29-36.webm](https://github.com/user-attachments/assets/154433a0-3daa-4f64-bc9e-2960e71eb26b)

**Comment by Fish1** [comment]
Does this still not work for you? I am unable to replicate this.

**Comment by Fish1** [comment]
Please reopen if you're having an issue still. I cannot replicate this.
