### ISSUE TITLE
YapMS crashes on Opera GX

### ISSUE THREAD

**Issue by jjcb123tree** [yapms/YAPms#784]
Anytime I simply hover my mouse over the candidates it causes the page to crash. It only seems to be with the candidates, and clicking or hovering over them causes the website to crash. Other browsers work, and it is just on Opera that this happens.

**Comment by jjjclarke** [comment]
Hearing this a lot. I can't confirm directly at the moment since Opera GX is not on Linux, but I hear that this issue does **not** affect standard Opera. I'll create a virtual machine later to try and get more info.

**Comment by Fish1** [comment]
Does it work now? I think Opera made an update that fixes this. I didn't do anything except update a few dependencies.

**Comment by jjcb123tree** [comment]
No, it still crashes on Opera GX.

**Comment by Fish1** [comment]
What version of OperaGX are you on? Is it the latest?

**Comment by Iionccub365** [comment]
I'm not having any issues personally

**Comment by Fish1** [comment]
Please reopen if this is still an issue. I cannot reproduce it.
