### ISSUE TITLE
Folder Naming Conventions

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#84]
Should the folder naming convention be changed? Right now it's all lowercase. I think it looked good for 1 or 2 word names. But when you get to a 3 word folder name, it becomes a bit hard to read.

Right now our components are all pascal case, I just wanted to differentiate folders from files.

Maybe we can use snake case?

![image](https://user-images.githubusercontent.com/13600696/209673567-670f8413-ca95-4683-a366-7c34f073c0c9.png)

**Comment by Flizzyclone** [comment]
I would prefer camel case personally, but I don't mind snake case at all if that is the direction we want to go.
