### ISSUE TITLE
state simulation voting

### ISSUE THREAD

**Issue by efefury** [yapms/YAPms#91]
show how close the state was in the simulation with the colors

**Comment by Fish1** [comment]
Currently, there isn't even an issue for the creation of the simulation. And the simulation that is planned is simply a random number generator.

This probably wont be worked on, unless we can find someone with the knowledge to create a realistic election simulation. I do not personally have the ability to do that.

**Comment by Flizzyclone** [comment]
Maybe in the future if we want to do this we can have margins be determined within some tolerance based on 2020 margin or something. So for example PA would range from R+5 to D+7 or something based on a randomly determined popular vote.

**Comment by Fish1** [comment]
This can be reopened if it will be worked on.
