### ISSUE TITLE
Save Map To Json

### ISSUE THREAD

**Issue by Fish1** [yapms/YAPms#95]
Add functionality to save the map to JSON format.

Allow the user to download this data to their computer.

**Comment by Flizzyclone** [comment]
Do we not want to have the map just save to SVG? We can save using attributes and that way we don't have to parse back and forth between JSON and SVG.

**Comment by Fish1** [comment]
We wouldn't want to allow users to upload SVG data because...

1) it would cause a huge amount of duplicated data, taking up storage space
2) it would allow users to upload HTML data, allowing for DOM manipulation, and open the website up to XSS attacks. Also people could upload inappropriate images.
