### ISSUE TITLE
Request: Add live election results

### ISSUE THREAD

**Issue by fdezwonders** [yapms/YAPms#981]
Yes, I know it is literally less than 24 hours before the US elections, but by any chance could you guys add a map that live updates the election results? I'm pretty sure [Decision Desk HQ](https://ddhq.io/results/2024/General/) has a API-friendly way to getting election results, but there is always the option to scrape their website or [The AP's website](https://apnews.com/projects/election-results-2024/)?

**Comment by Fish1** [comment]
It's currently too expensive to get an API. And scraping websites is most likely illegal.

**Comment by fdezwonders** [comment]
Oh, ok, sorry for wasting your time! Still tho, it would be pretty cool! Also, (if anyone is interested), [DDHQ's results](https://ddhq.io/results/2024/General/) are actually very good in general. Thanks!

**Comment by fdezwonders** [comment]
Oh, ok, sorry for wasting your time! Still tho, it would be pretty cool! Also, (if anyone is interested), [DDHQ's results](https://ddhq.io/results/2024/General/) are actually very good in general. Thanks!
